### ISSUE TITLE
No Macbook Pro M1/M2 support ?

### ISSUE THREAD

**Issue by peimansh** [m3o/m3o-cli#8]
When I try to install the CLI, I get this error message:

```
curl -fssl https://install.m3o.com/cli | /bin/bash
Getting system information
Your machine is running darwin on arm64 CPU architecture
Checking machine system support
No prebuilt binary for darwin-arm64
Failed to install m3o

```

**Comment by asim** [comment]
Install script is just missing the arch. Try again.

**Comment by peimansh** [comment]
Now it works,
But isn't it supposed to install the cli under /bin or /usr/local/bin ?
Seems like it puts all the files in the current working directory

**Comment by asim** [comment]
It installs under $HOME/bin
